namespace CapaDominio.Errors
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorsCodes
    {

        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;


        internal ErrorsCodes()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaDominio.Errors.ErrorsCodes", typeof(ErrorsCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture!;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200
        {
            get
            {
                return ResourceManager.GetString("200", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200A
        {
            get
            {
                return ResourceManager.GetString("200A", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200B
        {
            get
            {
                return ResourceManager.GetString("200B", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200C
        {
            get
            {
                return ResourceManager.GetString("200C", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200D
        {
            get
            {
                return ResourceManager.GetString("200D", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200E
        {
            get
            {
                return ResourceManager.GetString("200E", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200F
        {
            get
            {
                return ResourceManager.GetString("200F", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El resultado de la operacion de &apos;{0}&apos; ha sido satisfactoria.
        /// </summary>
        public static string _200G
        {
            get
            {
                return ResourceManager.GetString("200G", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se recibieron parámetros.
        /// </summary>
        public static string _400
        {
            get
            {
                return ResourceManager.GetString("400", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El número de Puerto debe ser válido y distinto de 0..
        /// </summary>
        public static string _400A
        {
            get
            {
                return ResourceManager.GetString("400A", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Servidor, Puerto, Usuario y Contraseña son datos obligatorios..
        /// </summary>
        public static string _400B
        {
            get
            {
                return ResourceManager.GetString("400B", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to El NIT ingresado no existe..
        /// </summary>
        public static string _400C
        {
            get
            {
                return ResourceManager.GetString("400C", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La cuenta de Correo que desea registrar esta asociada a otro NIT..
        /// </summary>
        public static string _400D
        {
            get
            {
                return ResourceManager.GetString("400D", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NIT es un campo obligatorio..
        /// </summary>
        public static string _400E
        {
            get
            {
                return ResourceManager.GetString("400E", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo asociar los parámetros recibidos con el objeto tipo &apos;{0}&apos;..
        /// </summary>
        public static string _400Ex1
        {
            get
            {
                return ResourceManager.GetString("400Ex1", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TipoIdentificacion un campo es obligatorio..
        /// </summary>
        public static string _400F
        {
            get
            {
                return ResourceManager.GetString("400F", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400G
        {
            get
            {
                return ResourceManager.GetString("400G", resourceCulture) ?? "";
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400H
        {
            get
            {
                return ResourceManager.GetString("400H", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400I
        {
            get
            {
                return ResourceManager.GetString("400I", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400J
        {
            get
            {
                return ResourceManager.GetString("400J", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400K
        {
            get
            {
                return ResourceManager.GetString("400K", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400L
        {
            get
            {
                return ResourceManager.GetString("400L", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400M
        {
            get
            {
                return ResourceManager.GetString("400M", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400N
        {
            get
            {
                return ResourceManager.GetString("400N", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400O
        {
            get
            {
                return ResourceManager.GetString("400O", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400P
        {
            get
            {
                return ResourceManager.GetString("400P", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400Q
        {
            get
            {
                return ResourceManager.GetString("400Q", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se encontro registro para &apos;{0}&apos;. Verificar los datos de entrada.
        /// </summary>
        public static string _400R
        {
            get
            {
                return ResourceManager.GetString("400R", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo autenticar el usuario de la cuenta de correo &apos;{0}&apos; con las credenciales proporcionadas.
        /// </summary>
        public static string _401
        {
            get
            {
                return ResourceManager.GetString("401", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer conexión con el servidor de la cuenta de correo &apos;{0}&apos;.
        /// </summary>
        public static string _500
        {
            get
            {
                return ResourceManager.GetString("500", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se puede procesar. Error general.
        /// </summary>
        public static string _500A
        {
            get
            {
                return ResourceManager.GetString("500A", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fallo la creación de las carpetas en la cuenta de correo del usuario &apos;{0}&apos;..
        /// </summary>
        public static string _500B
        {
            get
            {
                return ResourceManager.GetString("500B", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fallo la creación de las carpetas en la cuenta de correo del usuario &apos;{0}&apos;..
        /// </summary>
        public static string _500C
        {
            get
            {
                return ResourceManager.GetString("500C", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hubo un problema registrando en la base de datos..
        /// </summary>
        public static string _500D
        {
            get
            {
                return ResourceManager.GetString("500D", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión a la base de datos.
        /// </summary>
        public static string _500E
        {
            get
            {
                return ResourceManager.GetString("500E", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión a la base de datos.
        /// </summary>
        public static string _500F
        {
            get
            {
                return ResourceManager.GetString("500F", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión a la base de datos.
        /// </summary>
        public static string _500G
        {
            get
            {
                return ResourceManager.GetString("500G", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión a la base de datos.
        /// </summary>
        public static string _500H
        {
            get
            {
                return ResourceManager.GetString("500H", resourceCulture) ?? "";
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión a la base de datos.
        /// </summary>
        public static string _500I
        {
            get
            {
                return ResourceManager.GetString("500I", resourceCulture) ?? "";
            }
        }
    }
}

