//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Mensajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Mensajes.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proveedor se activó correctamente!.
        /// </summary>
        public static string ProcesoActivacionCompletado {
            get {
                return ResourceManager.GetString("ProcesoActivacionCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al tratar de activar el proveedor {0}  con el receptor {1} por favor validar que sean identificadores válidos..
        /// </summary>
        public static string ProcesoActivacionError_1 {
            get {
                return ResourceManager.GetString("ProcesoActivacionError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de ejecutar Store procedure de activación de proveedores..
        /// </summary>
        public static string ProcesoActivacionLog_2 {
            get {
                return ResourceManager.GetString("ProcesoActivacionLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar proveedores.
        /// </summary>
        public static string ProcesoActivacionProveedores {
            get {
                return ResourceManager.GetString("ProcesoActivacionProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de iniciar proceso de activación de proveedores..
        /// </summary>
        public static string ProcesoActivacionProveedoresLog_1 {
            get {
                return ResourceManager.GetString("ProcesoActivacionProveedoresLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceso de paginación..
        /// </summary>
        public static string ProcesoPaginacion {
            get {
                return ResourceManager.GetString("ProcesoPaginacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consulta fue exitosa se recuperaron {0} de registros de {1}..
        /// </summary>
        public static string ProcesoPaginacionCompletado {
            get {
                return ResourceManager.GetString("ProcesoPaginacionCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El resultado de la consulta es null..
        /// </summary>
        public static string ProcesoPaginaciónError_1 {
            get {
                return ResourceManager.GetString("ProcesoPaginaciónError_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La consulta no arrojo resultados..
        /// </summary>
        public static string ProcesoPaginaciónError_2 {
            get {
                return ResourceManager.GetString("ProcesoPaginaciónError_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la ejecución, Error: {0}.
        /// </summary>
        public static string ProcesoPaginaciónError_3 {
            get {
                return ResourceManager.GetString("ProcesoPaginaciónError_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de retornar respuesta, total registros a devolver {0}.
        /// </summary>
        public static string ProcesoPaginacionLog_1 {
            get {
                return ResourceManager.GetString("ProcesoPaginacionLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de consultar proveedores para el usuario {0}.
        /// </summary>
        public static string ProcesoPaginacionLog_2 {
            get {
                return ResourceManager.GetString("ProcesoPaginacionLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despues de consultar proveedores, registros obtenidos {0}.
        /// </summary>
        public static string ProcesoPaginacionLog_3 {
            get {
                return ResourceManager.GetString("ProcesoPaginacionLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vincular usuarios y proveedores..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de ejecutar la relación en la base de datos..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log1 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la asociación de proveedores error: {1}.
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log2 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despues de ejecutar la consulta en la base de datos, codigo de resultado = {0}..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log3 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de ejecutar SP assign_providers_to_users..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log4 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total provedores a asociar {0}..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log5 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despues de ejecutar la consulta en la base de datos, resultado = {0}. .
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log6 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunas relaciones no se ejecutaron, debido a que los identificadores de los proveedores no son correctos..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log7 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ejecución no arrojó resultados..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log8 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la asociación de usuarios y proveedores..
        /// </summary>
        public static string ProcesoVincularUsuariosProveedores_log9 {
            get {
                return ResourceManager.GetString("ProcesoVincularUsuariosProveedores_log9", resourceCulture);
            }
        }
    }
}
